version: "3.8"

services:

  app:
    build: .
    container_name: kalenderbali_app
    restart: unless-stopped
    expose:
      - "80"

  caddy:
    image: caddy:2
    container_name: KalenderBali
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    depends_on:
      - app

volumes:
  caddy_data:
  caddy_config:
