services:
  kalenderbali:
    build:
      context: .
      dockerfile: Dockerfile
    image: kalenderbali:latest
    container_name: kalenderbali
    restart: unless-stopped
    ports:
      - "3080:80"
    environment:
      - TZ=Asia/Makassar
