services:
  kalenderbali:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: kalenderbali
    restart: unless-stopped
    ports:
      - "3080:80"
    networks:
      - caddy_net

networks:
  caddy_net:
    external: true
