server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Mengarahkan semua request ke index.html agar client-side routing (React Router dll) tetap jalan
        try_files $uri $uri/ /index.html;
    }

    # Handling error page
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}
